name = "404-error-page"
compatibility_date = "2024-08-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = ["*/*"]

# build configuration
[build]
command = "echo 'no build required'"

# functions directory
[functions]
directory = "functions"